services:
  spark-master:
    image: apache/spark:4.1.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - "spark-data:/opt/spark/work-dir"
    entrypoint:
      - "bash"
      - "-c" 
      - "/opt/spark/sbin/start-master.sh && tail -f /dev/null"

  spark-connect:
    image: apache/spark:4.1.1
    container_name: spark-connect
    hostname: spark-connect
    ports:
      - "4040:4040"
      - "15002:15002"
    depends_on:
      - spark-master
    volumes:
      - "spark-data:/opt/spark/work-dir"
    command: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 && tail -f /dev/null"

  spark-worker:
    image: apache/spark:4.1.1
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081-8084:8081"
    volumes:
      - "spark-data:/opt/spark/work-dir"
    command:
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

volumes:
  spark-data:
